// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: packages/contracts/out (Foundry artifacts). Regenerate with `pnpm abis:generate`.
//
// ABIs come from the compiled contracts, never from hand-written signatures
// (llm.txt s6, s66). apps/web, apps/api and apps/indexer all read this one copy.
export {arkSwapFactoryAbi} from './ArkSwapFactory';
export {arkSwapPairAbi} from './ArkSwapPair';
export {arkSwapRouter02Abi} from './ArkSwapRouter02';
export {erc20Abi} from './ERC20';

/** keccak256(type(ArkSwapPair).creationCode) — CREATE2 pair derivation (llm.txt s7). */
export const PAIR_INIT_CODE_HASH = '0x30820c342fc28c16c80e536d138c0c5290a90de3583c2a126a9e19b519432e74' as const;
