#!/usr/bin/env node
/**
 * Generate packages/abis from the REAL Foundry artifacts in packages/contracts/out.
 *
 * llm.txt s6 and s66 require ABIs generated from the actual ArkSwap contracts
 * rather than hand-written signatures, and the monorepo rules require apps/web,
 * apps/api and apps/indexer to consume one shared copy instead of duplicating
 * them. This script is the only writer of packages/abis.
 *
 *   pnpm abis:generate
 */
import {execFileSync} from 'node:child_process';
import {mkdirSync, readFileSync, writeFileSync, existsSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** ArkSwapFactory -> arkSwapFactory, ERC20 -> erc20 */
const lower = (n) => (n === 'ERC20' ? 'erc20' : n[0].toLowerCase() + n.slice(1));
const out = join(root, 'packages/contracts/out');
const dest = join(root, 'packages/abis');

// name -> artifact path. IERC20 gives a clean ERC-20 surface without pulling in
// a mock's faucet mint(), which must never appear in a shared ABI.
const TARGETS = {
  ArkSwapFactory: 'ArkSwapFactory.sol/ArkSwapFactory.json',
  ArkSwapPair: 'ArkSwapPair.sol/ArkSwapPair.json',
  ArkSwapRouter02: 'ArkSwapRouter02.sol/ArkSwapRouter02.json',
  ERC20: 'IERC20.sol/IERC20.json',
};

if (!existsSync(out)) {
  console.error(`error: ${out} not found — run "pnpm contracts:build" first`);
  process.exit(1);
}

mkdirSync(dest, {recursive: true});
const written = [];

for (const [name, rel] of Object.entries(TARGETS)) {
  const path = join(out, rel);
  if (!existsSync(path)) {
    console.error(`error: missing artifact ${rel} — run "pnpm contracts:build" first`);
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) {
    console.error(`error: ${rel} has no ABI`);
    process.exit(1);
  }
  // JSON for the Go apps (go-ethereum's abi.JSON reader) ...
  writeFileSync(join(dest, `${name}.json`), `${JSON.stringify(artifact.abi, null, 2)}\n`);
  // ... and TypeScript with `as const`, which viem needs to infer argument and
  // return types. Same bytes, two consumers, one generator.
  writeFileSync(
    join(dest, `${name}.ts`),
    `// GENERATED by scripts/generate-abis.mjs — do not edit.\n` +
      `export const ${lower(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  written.push({name, entries: artifact.abi.length});
}

// Also publish the pair init-code hash, so every consumer derives CREATE2 pair
// addresses from one value instead of copying a constant around (llm.txt s7).
const pairArtifact = JSON.parse(readFileSync(join(out, TARGETS.ArkSwapPair), 'utf8'));
const creationCode = pairArtifact.bytecode?.object;
if (!creationCode || !creationCode.startsWith('0x')) {
  console.error('error: could not read ArkSwapPair creation code');
  process.exit(1);
}
// Hashed with `cast keccak` rather than a JS keccak dependency: it is the same
// tool packages/contracts uses to produce the constant baked into ArkSwapLibrary,
// so there is exactly one implementation deciding this value.
const initCodeHash = execFileSync('cast', ['keccak', creationCode], {encoding: 'utf8'}).trim();
if (!/^0x[0-9a-f]{64}$/.test(initCodeHash)) {
  console.error(`error: unexpected cast keccak output: ${initCodeHash}`);
  process.exit(1);
}

writeFileSync(
  join(dest, 'pair-init-code-hash.json'),
  `${JSON.stringify({pairInitCodeHash: initCodeHash}, null, 2)}\n`,
);

const index = `// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: packages/contracts/out (Foundry artifacts). Regenerate with \`pnpm abis:generate\`.
//
// ABIs come from the compiled contracts, never from hand-written signatures
// (llm.txt s6, s66). apps/web, apps/api and apps/indexer all read this one copy.
${Object.keys(TARGETS)
  .map((n) => `export {${lower(n)}Abi} from './${n}';`)
  .join('\n')}

/** keccak256(type(ArkSwapPair).creationCode) — CREATE2 pair derivation (llm.txt s7). */
export const PAIR_INIT_CODE_HASH = '${initCodeHash}' as const;
`;
writeFileSync(join(dest, 'index.ts'), index);

console.log('packages/abis written from packages/contracts/out:');
for (const w of written) console.log(`  ${w.name.padEnd(18)} ${w.entries} ABI entries`);
console.log(`  PAIR_INIT_CODE_HASH ${initCodeHash}`);
