#!/usr/bin/env bash
# Install emscripten (solc-js) builds of the exact compiler versions ArkSwap
# pins, and register them with svm so Foundry picks them up.
#
# Needed on arm64 macOS, where solc 0.5.16 / 0.6.6 have no native binary and
# Rosetta 2 may be unavailable. Safe to re-run. Any pre-existing native binary
# is preserved as solc-<version>.native.bak rather than deleted.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS=("0.5.16" "0.6.6")

for v in "${VERSIONS[@]}"; do
  echo "==> solc ${v}"
  dir="${ROOT}/tools/solc/${v}"
  mkdir -p "${dir}"
  if [ ! -f "${dir}/package.json" ]; then
    cat > "${dir}/package.json" <<JSON
{
  "name": "arkswap-solc-${v}",
  "private": true,
  "description": "Pinned emscripten solc ${v} used by tools/solc-shim.js",
  "dependencies": {"solc": "${v}"}
}
JSON
  fi
  (cd "${dir}" && npm install --silent --no-audit --no-fund >/dev/null)

  svmdir="${HOME}/.svm/${v}"
  mkdir -p "${svmdir}"
  target="${svmdir}/solc-${v}"
  if [ -f "${target}" ] && ! head -c 2 "${target}" | grep -q '#!'; then
    echo "    preserving existing native binary -> solc-${v}.native.bak"
    mv "${target}" "${svmdir}/solc-${v}.native.bak"
  fi
  cat > "${target}" <<SH
#!/bin/sh
# Generated by ArkSwap tools/install-solc.sh -- do not edit.
ARKSWAP_SOLC_VERSION="${v}" exec node "${ROOT}/tools/solc-shim.js" "\$@"
SH
  chmod +x "${target}"
  echo "    $(${target} --version | tail -1)"
done

echo "Done."
